import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import GooeyBackground from '../components/GooeyBackground'; // Import your background component

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GooeyBackground /> {/* Render the background component here */}
        <div className="relative z-10"> {/* Wrap your content to be above the background */}
          {children}
        </div>
      </body>
    </html>
  );
}
